# Author: kmmcelro
# This task is apart of the ProjectEuler+ Contest on Hackerrank
# This is my solution to Project Euler #2: Even Fibonacci Numbers
# link: https://www.hackerrank.com/contests/projecteuler/challenges/euler002/problem

""""
Task
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89

By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.
"""


#!/bin/python3

import sys


t = int(input().strip()) # number of test cases
for a0 in range(t):
    n = int(input().strip()) # upper bound for the sequence
    fib = 1 
    lastfib = 0
    fibsum = 0
    while fib <= n:
        if fib % 2 == 0: # Checking if the current fibonacci number is even and adds it to the sum if it is
            fibsum += fib
        # Calculating the next fibonacci number
        fib += lastfib 
        lastfib = fib - lastfib
    print(fibsum)
